  export const SET_ROOMS = 'SET_ROOMS'
  export const SET_USERS = 'SET_USERS'
  export const SET_SOCKET = 'SET_SOCKET'
  export const REMOVE_ALL = 'REMOVE_ALL'
  export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM'
  export const SET_MESSAGE = 'SET_MESSAGE'
  export const ROOM_CHANGED = 'ROOM_CHANGED'
  export const ADD_ROOM = 'ADD_ROOM'
  export const NEW_ROOM_CREATED = 'NEW_ROOM_CREATED'
  export const DIRECT_MESSAGE_ROOM = 'DIRECT_MESSAGE_ROOM'
  export const UPDATE_MESSAGE = 'UPDATE_MESSAGE'
  export const USER_REGISTRATION = 'USER_REGISTRATION'
  export const USER_REGISTER = 'USER_REGISTER'
  export const SET_USER = 'SET_USER'


  export const GET_MESSAGES = 'GET_MESSAGES'
  export const MESSAGES = 'MESSAGES'
  export const NEW_MESSAGE = 'NEW_MESSAGE'

  export const ROOMS = 'ROOMS'
  export const UPDATE_USER = 'UPDATE_USER'
  export const USER = 'USER'
  export const USERS = 'USERS'
